title: inventory
type: object
description: Reader settings for inventory mode.
properties:
  interval:
    type: object
    description: The interval (in seconds) at which a tag is reported - provided it is still being read.
    properties:
      unit:
        type: string
        enum:
          - seconds
          - minutes
          - hours
          - days
      value:
        type: integer
